# Generated by Django 5.1.1 on 2024-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('categoria', models.CharField(choices=[('E', 'Eletronicos'), ('D', 'Domésticos'), ('CMB', 'Casa, Mesa e Banho')], max_length=5)),
                ('localizacao', models.CharField(choices=[('R1', 'Rua 1'), ('R2', 'Rua 2'), ('R3', 'Rua 3')], max_length=5)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
