# Generated by Django 5.1.1 on 2024-09-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_historicalproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduto',
            name='_change_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='_change_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
