# Generated by Django 5.1.1 on 2024-09-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_historicalproduto__change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduto',
            name='_change_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razão da alteração'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='nome',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='_change_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razão da alteração'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do Produto'),
        ),
    ]
