# Generated by Django 5.1.1 on 2024-09-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_historicalproduto__change_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduto',
            name='_change_reason',
            field=models.CharField(blank=True, choices=[('C', 'Compra'), ('V', 'Venda')], default='Criar', max_length=255, verbose_name='Razão da alteração'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='_change_reason',
            field=models.CharField(blank=True, choices=[('C', 'Compra'), ('V', 'Venda')], default='Criar', max_length=255, verbose_name='Razão da alteração'),
        ),
    ]
